#
# Copyright (c) 2020, 2025, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

# Versions and download locations for dependencies used by GitHub Actions (GHA)

BOOT_JDK_VERSION=17
GTEST_VERSION=1.13.0
JTREG_VERSION=7.5.2+1

LINUX_X64_BOOT_JDK_FILENAME=openjdk-17.0.6_linux-x64_bin.tar.gz
LINUX_X64_BOOT_JDK_EXT=tar.gz
LINUX_X64_BOOT_JDK_URL=https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.19%2B10/OpenJDK17U-jdk_x64_linux_hotspot_17.0.19_10.tar.gz
LINUX_X64_BOOT_JDK_SHA256=d8afc263758141a66e0e3aafc321e783f7016696f4eaea067d340a269037d331


MACOS_AARCH64_BOOT_JDK_FILENAME=openjdk-17.0.6_macos-aarch64_bin.tar.gz
MACOS_AARCH64_BOOT_JDK_EXT=tar.gz
MACOS_AARCH64_BOOT_JDK_URL=https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.19%2B10/OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.19_10.tar.gz
MACOS_AARCH64_BOOT_JDK_SHA256=8fa1eff40bb637a33613b2ccb8b12c70dc3661cc22cf8e784943715769a05336

MACOS_X64_BOOT_JDK_FILENAME=openjdk-17.0.6_macos-x64_bin.tar.gz
MACOS_X64_BOOT_JDK_EXT=tar.gz
MACOS_X64_BOOT_JDK_URL=https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.19%2B10/OpenJDK17U-jdk_x64_mac_hotspot_17.0.19_10.tar.gz
MACOS_X64_BOOT_JDK_SHA256=03632d1fbf139ab3719a9f4b47dc206251449b87557143c822336dbf8c06560f

WINDOWS_X64_BOOT_JDK_FILENAME=openjdk-17.0.6_windows-x64_bin.zip
WINDOWS_X64_BOOT_JDK_EXT=zip
WINDOWS_X64_BOOT_JDK_URL=https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.19%2B10/OpenJDK17U-jdk_x64_windows_hotspot_17.0.19_10.zip
WINDOWS_X64_BOOT_JDK_SHA256=b5b235c48adf6a081874b812c630b9f4b5f637b7a5ed18b9174d08a41ec4c235
